name: e_learning_center_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase
  firebase_auth: ^3.9.0
  firebase_database: ^9.1.4
  cloud_firestore: ^3.4.8
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8

  # network
  http: ^0.13.5

  # state management
  provider: ^6.0.3

  # animations
  flutter_staggered_animations: ^1.1.1

  # images
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
